<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>82fc24af-6148-45c6-8893-994171d7b165</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Dapr" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SudokuDaprActors.Api\SudokuDaprActors.Api.csproj" />
    <ProjectReference Include="..\SudokuDaprActors.Cells\SudokuDaprActors.Cells.csproj" />
    <ProjectReference Include="..\SudokuDaprActors.Web\SudokuDaprActors.Web.csproj" />
  </ItemGroup>

</Project>
