<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Dapr.Actors.AspNetCore" />
    <PackageReference Include="Dapr.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SudokuDaprActors.Cells.Contracts\SudokuDaprActors.Cells.Contracts.csproj" />
    <ProjectReference Include="..\SudokuDaprActors.ServiceDefaults\SudokuDaprActors.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
