<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SudokuDaprActors.ServiceDefaults\SudokuDaprActors.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
